package Avion;

import Reservation.*;
import Vol.JVol;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jospin
 */
public class Accueil extends javax.swing.JFrame {

    private Connection con=null;
    private PreparedStatement pst=null;
    private ResultSet rs=null;
    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        con=avionDB.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        avion_btn = new javax.swing.JButton();
        reservation_btn = new javax.swing.JButton();
        vol_btn = new javax.swing.JButton();
        histogramme_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACCUEIL");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AIR MAD");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 280, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenue parmi nous!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 30));

        avion_btn.setBackground(new java.awt.Color(102, 102, 255));
        avion_btn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        avion_btn.setText("AVION");
        avion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avion_btnActionPerformed(evt);
            }
        });
        jPanel1.add(avion_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 270, -1));

        reservation_btn.setBackground(new java.awt.Color(102, 102, 255));
        reservation_btn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        reservation_btn.setText("RESERVATION");
        reservation_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reservation_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 270, -1));

        vol_btn.setBackground(new java.awt.Color(102, 102, 255));
        vol_btn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        vol_btn.setText("VOL");
        vol_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vol_btnActionPerformed(evt);
            }
        });
        jPanel1.add(vol_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, -1));

        histogramme_btn.setBackground(new java.awt.Color(102, 102, 255));
        histogramme_btn.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        histogramme_btn.setText("HISTOGRAMME");
        histogramme_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histogramme_btnActionPerformed(evt);
            }
        });
        jPanel1.add(histogramme_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(558, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void avion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avion_btnActionPerformed
        // TODO add your handling code here:
        Menu m= new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_avion_btnActionPerformed

    private void reservation_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation_btnActionPerformed
        JReservation res=new JReservation();
        res.setVisible(true);
    }//GEN-LAST:event_reservation_btnActionPerformed

    private void vol_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vol_btnActionPerformed
        JVol v= new JVol();
        v.setVisible(true);
    }//GEN-LAST:event_vol_btnActionPerformed

    private void histogramme_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histogramme_btnActionPerformed
        String annee=JOptionPane.showInputDialog("Veuillez entrer un année:");
        if(!annee.equals("")){
            String req="SELECT  SUM(VOL.frais) AS recette, AVION.NumAvion FROM AVION,RESERVATION,VOL WHERE (VOL.NumVol=AVION.NumVol) AND (AVION.NumAVion=RESERVATION.NumAvion) AND (STRFTIME(\"%Y\",RESERVATION.Date_Reservation))=\""+annee+"\" GROUP BY AVION.NumAVION";
            DefaultCategoryDataset dataset=new DefaultCategoryDataset();
            try {
                pst=con.prepareStatement(req);
                rs=pst.executeQuery();
                while(rs.next()){
                    dataset.setValue(rs.getDouble("recette"),"RECETTE",rs.getString("NumAvion"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        
        
            JFreeChart chart=ChartFactory.createBarChart("RECETTE ANNUELLE PAR AVION", "Numero Avion", "Recette", dataset, PlotOrientation.VERTICAL, false, true, false);
        //CategoryPlot p=chart.getCategoryPlot();
        //p.setRangeGridlinePaint(Color.red);
            ChartFrame frame=new ChartFrame("RECETTE ANNUELLE PAR AVION",chart);
            frame.setSize(450,350);
            frame.setLocationRelativeTo(null);

            frame.setVisible(true);
        }
        
    }//GEN-LAST:event_histogramme_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avion_btn;
    private javax.swing.JButton histogramme_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reservation_btn;
    private javax.swing.JButton vol_btn;
    // End of variables declaration//GEN-END:variables
}
