package Avion;


import Avion.Menu;
import Reservation.avionDB;
import com.sun.tools.javac.util.StringUtils;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jospin
 */
public class Ajout extends javax.swing.JFrame {

    /**
     * Creates new form Ajout
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet resultat= null;
    Menu men=null;
    public Ajout(Menu menu) {
        initComponents();
        conn=avionDB.ConnectDB();
        men=menu;
        numAvions.setText(suggestion_Id("AV"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numVols = new javax.swing.JTextField();
        numAvions = new javax.swing.JTextField();
        designation = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        VALIDER = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AIR MAD");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Numéro du vol :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Numéro de l'avion :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Désignation :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre de places :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        numVols.setBackground(new java.awt.Color(204, 204, 204));
        numVols.setBorder(null);
        numVols.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numVols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numVolsActionPerformed(evt);
            }
        });
        jPanel1.add(numVols, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, 30));

        numAvions.setBackground(new java.awt.Color(204, 204, 204));
        numAvions.setBorder(null);
        numAvions.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        numAvions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAvionsActionPerformed(evt);
            }
        });
        jPanel1.add(numAvions, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 30));

        designation.setBackground(new java.awt.Color(204, 204, 204));
        designation.setBorder(null);
        designation.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationActionPerformed(evt);
            }
        });
        jPanel1.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 180, 30));

        nombre.setBackground(new java.awt.Color(204, 204, 204));
        nombre.setBorder(null);
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, 30));

        VALIDER.setBackground(new java.awt.Color(204, 204, 204));
        VALIDER.setFont(new java.awt.Font("Snap ITC", 0, 14)); // NOI18N
        VALIDER.setForeground(new java.awt.Color(51, 51, 51));
        VALIDER.setText("VALIDER");
        VALIDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALIDERActionPerformed(evt);
            }
        });
        jPanel1.add(VALIDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 180, 40));

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });
        jPanel1.add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 30, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(527, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numVolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numVolsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numVolsActionPerformed

    private void numAvionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAvionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numAvionsActionPerformed

    private void designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed
    public boolean already_exist(String numAvion){
            String requete="SELECT * FROM AVION WHERE NumAvion='"+numAvion+"'";
            boolean Vret=false;
            try{
                pst=conn.prepareStatement(requete);
                resultat= pst.executeQuery();
                if(resultat.next()){
                    Vret= true;
                }
                else{
                    Vret= false;
                }
                resultat.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            
            return Vret;
    }
    
    public String suggestion_Id(String deb){
		int i=1;
		StringBuilder id=new StringBuilder();
		id.append(deb);
		id.append(i);
		while(already_exist(id.toString())) {
			id.delete(0, id.length());
			i++;
			id.append(deb);
			id.append(i);
		}
		return id.toString();
    }
    public boolean vol_exist(String NumVol){
        String requete="SELECT * FROM VOL WHERE NumVol='"+NumVol+"'";
                    boolean Vret=false;
            try{
                pst=conn.prepareStatement(requete);
                resultat= pst.executeQuery();
                if(resultat.next()){
                    Vret= true;
                }
                else{
                    Vret= false;
                }
                resultat.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            
            return Vret;    
    }
    private boolean valid_nbplace(String nb){
        boolean ret=false;
        if(nb.matches("[+-]?\\d*(\\.\\d+)?")){
            ret=true;
        }else{
            JOptionPane.showMessageDialog(null ,"Le nombre de place doit être un nombre");
        }
        return ret;
    }
    private void VALIDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALIDERActionPerformed
        // TODO add your handling code here:
        String numAvion = numAvions.getText();
        String design= designation.getText();
        String nbPlaces= nombre.getText();
        String numVol= numVols.getText();
        
        
        
        String requete="INSERT INTO AVION(NumAvion,Design,NbPlaces,NumVol) VALUES (?,?,?,?)";
        if("".equals(numAvion) || "".equals(design) || "".equals(nbPlaces) || "".equals(numVol)){
            JOptionPane.showMessageDialog(null,"Le formulaire est incomplet");
        }
        else{
            if(already_exist(numAvion)){
                JOptionPane.showMessageDialog(null,"Il paraît que l'un ou tout ce que tu as saisi est déjà existé");
                }
            else{
                if(vol_exist(numVol)&&valid_nbplace(nbPlaces)){
                    try{
                        pst=conn.prepareStatement(requete);
                        pst.setString(1,numAvion);
                        pst.setString(2, design);
                        pst.setString(3, nbPlaces);
                        pst.setString(4, numVol);
    
                        //System.out.println("MIlamina tsara");
                        pst.execute();
                        pst.close();
                        StringBuilder NumPl=new StringBuilder();
                        for(int i=1;i<=Integer.parseInt(nbPlaces);i++) {
                            NumPl.append("PL");
                            NumPl.append(i);
                            requete="INSERT INTO PLACE(NumAvion,NumPlace,Occupation,NumReservation) VALUES (?,?,?,?)";
                            try{
                                pst=conn.prepareStatement(requete);
                                pst.setString(1,numAvion);
                                pst.setString(2, NumPl.toString());
                                pst.setInt(3, 0);
                                pst.setString(4, "");
                                pst.executeUpdate();
                                pst.close();
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,e);
                            }
                            NumPl.delete(0, NumPl.length());
                        }
                        JOptionPane.showMessageDialog(null,"Ajouté avec succès");
                        men.listeAvions();
                        setVisible(false);
                    }catch(HeadlessException | SQLException e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Numéro vol n'existe pas");
                }
                
            }
        }
    }//GEN-LAST:event_VALIDERActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VALIDER;
    private javax.swing.JTextField designation;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numAvions;
    private javax.swing.JTextField numVols;
    // End of variables declaration//GEN-END:variables
}
