package Avion;


import Avion.Modification;
import Reservation.avionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jospin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet resultat= null;
    public Menu() {
        initComponents();
        conn=avionDB.ConnectDB();
        listeAvions();
    }
    
    public void listeAvions(){
    String requete = "SELECT * FROM AVION";
    try{
            pst= conn.prepareStatement(requete);
            resultat =pst.executeQuery();
            DefaultTableModel model=new DefaultTableModel(new String[]{"NumAvion","Design","NbPlaces","NumVol" },0)
            
            {
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(resultat.next()){
                model.addRow(new Object[]{
                 
                    resultat.getString("NumAvion"),
                    resultat.getString("Design"),
                    resultat.getString("NbPlaces"),
                    resultat.getString("NumVol")    
                });
            }
            listeAvions.setModel(model);
            listeAvions.setRowHeight(25);
        }catch(Exception e){
            e.printStackTrace();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        suppression = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ajout = new javax.swing.JButton();
        Modification = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeAvions = new javax.swing.JTable();
        Recette_btn = new javax.swing.JButton();
        Rechercher_form = new javax.swing.JTextField();
        place_btn = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();
        liberer_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(153, 255, 204));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suppression.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        suppression.setText("SUPPRIMER");
        suppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppressionActionPerformed(evt);
            }
        });
        jPanel2.add(suppression, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 130, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AIR MAD");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vous pouvez naviguer en cliquant ces boutons");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        ajout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ajout.setText("AJOUTER ");
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });
        jPanel2.add(ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 40));

        Modification.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Modification.setText("MODIFIER");
        Modification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificationActionPerformed(evt);
            }
        });
        jPanel2.add(Modification, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("LISTE DES AVIONS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 210, 30));

        listeAvions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listeAvions);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 610, 210));

        Recette_btn.setText("RECETTE");
        Recette_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recette_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Recette_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        Rechercher_form.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Rechercher_formKeyReleased(evt);
            }
        });
        jPanel2.add(Rechercher_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 90, -1));

        place_btn.setText("PLACE");
        place_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_btnActionPerformed(evt);
            }
        });
        jPanel2.add(place_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });
        jPanel2.add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 40));

        liberer_btn.setText("LIBERER");
        liberer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberer_btnActionPerformed(evt);
            }
        });
        jPanel2.add(liberer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(618, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void suppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppressionActionPerformed
        // TODO add your handling code here:
        String ID;
        String req;
        int confirmer=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer","SUPPRIMER",JOptionPane.YES_NO_OPTION);
        if(listeAvions.getSelectedRow()>=0){
            if(confirmer==0){
                try{
                    ID=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),0));
                    req="DELETE FROM AVION WHERE NumAvion='"+ID+"'";
                    pst=conn.prepareStatement(req);
                    pst.execute();
                    pst.close();
                    
                    pst=conn.prepareStatement("DELETE FROM PLACE WHERE NumAvion='"+ID+"'");
                    pst.execute();
                    pst.close();
                    
                    /**pst=conn.prepareStatement("DELETE FROM RESERVATION WHERE NumAvion='"+ID+"'");
                    pst.execute();
                    pst.close();*/
                    
                    JOptionPane.showMessageDialog(null,"Suppression effectuée");
                    listeAvions();
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }                              
        }
        else{
            JOptionPane.showMessageDialog(null,"Tu dois selectionner avant de supprimer");
        }
    }//GEN-LAST:event_suppressionActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
        // TODO add your handling code here:
        Ajout a= new Ajout(this);
        a.setVisible(true);
    }//GEN-LAST:event_ajoutActionPerformed

    private void ModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificationActionPerformed
        // TODO add your handling code here:
        String NumAvion, Design, NombrePlaces, NumVol;
        if(listeAvions.getSelectedRow()>=0){
            NumAvion=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),0));
            Design=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),1));
            NombrePlaces=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),2));
            NumVol=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),3));
        
            Modification mod= new Modification(NumAvion,Design,NombrePlaces,NumVol,this);
            mod.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Tu dois selectionner avant de modifier");
        }
    }//GEN-LAST:event_ModificationActionPerformed

    private void Recette_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recette_btnActionPerformed
       if(listeAvions.getSelectedRow()<0){
           JOptionPane.showMessageDialog(null,"Veuillez selectionner une avion");
       }
       else{
           String NumAvion=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),0));
           String Design=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),1));
           new Recette(NumAvion,Design).show();
       }
    }//GEN-LAST:event_Recette_btnActionPerformed

    private void Rechercher_formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rechercher_formKeyReleased
        String search=Rechercher_form.getText();
        String req="SELECT * FROM AVION WHERE NumAvion LIKE'%"+search+"%'OR Design LIKE '%"+search+"%' OR NbPlaces LIKE '%"+search+"%' OR NumVol LIKE '%"+search+"%'";
        try{
            pst=conn.prepareStatement(req);
            resultat=pst.executeQuery();
            //int i=1;
            DefaultTableModel model=new DefaultTableModel(new String[]{
               "NumAvion","Design","NbPlaces","NumVol" 
            },0){
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(resultat.next()){
                model.addRow(new Object[]{
                    resultat.getString("NumAvion"),
                    resultat.getString("Design"),
                    resultat.getString("NbPlaces"),
                    resultat.getString("NumVol")
                });
                //i++;
            }
            pst.close();
            resultat.close();
            listeAvions.setModel(model);
            listeAvions.setRowHeight(25);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Rechercher_formKeyReleased

    private void place_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_btnActionPerformed
        if(listeAvions.getSelectedRow()<0){
           JOptionPane.showMessageDialog(null,"Veuillez selectionner une avion");
       }
       else{
           String NumAvion=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),0));
           String Design=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),1));
           new Place(NumAvion,Design).show();
       }
    }//GEN-LAST:event_place_btnActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    private void liberer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberer_btnActionPerformed
        if(listeAvions.getSelectedRow()<0){
           JOptionPane.showMessageDialog(null,"Veuillez selectionner une avion");
       }
       else{
            
           String NumAvion=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),0));
           String Design=String.valueOf(listeAvions.getValueAt(listeAvions.getSelectedRow(),1));
           int confirmer=JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment liberer l'avion N°"+NumAvion+"","LIBERER",JOptionPane.YES_NO_OPTION); 
           if(confirmer==0){
               try {
                pst=conn.prepareStatement("UPDATE PLACE SET Occupation=0, NumReservation='' WHERE NumAvion='"+NumAvion+"'");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"L'avion N°"+NumAvion+" est liberé avec succès");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
           }
        }
    }//GEN-LAST:event_liberer_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modification;
    private javax.swing.JButton Recette_btn;
    private javax.swing.JTextField Rechercher_form;
    private javax.swing.JButton ajout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton liberer_btn;
    private javax.swing.JTable listeAvions;
    private javax.swing.JButton place_btn;
    private javax.swing.JButton suppression;
    // End of variables declaration//GEN-END:variables
}
