package Avion;


import Reservation.avionDB;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jospin
 */
public class Modification extends javax.swing.JFrame {

    /**
     * Creates new form Modification
     */
    Connection conn= null;
    PreparedStatement pst= null;
    ResultSet resultat= null;
    Menu men= null;
    String oldNumAvion;
    String oldNumVol;
    int oldNbPlace;
    
    public Modification(String NumAvion, String Design, String NombrePlaces, String NumVol, Menu m) {
        initComponents();
        conn=avionDB.ConnectDB();
        men = m;
        numAvion.setText(NumAvion);
        designation.setText(Design);
        nombrePlaces.setText(NombrePlaces);
        numVol.setText(NumVol);
        oldNumAvion= NumAvion;
        oldNumVol= NumVol;
        oldNbPlace=Integer.parseInt(NombrePlaces);
    }
    
    private boolean valid_nbplace(String nb){
        boolean ret=false;
        if(nb.matches("[+-]?\\d*(\\.\\d+)?")){
            ret=true;
        }else{
            JOptionPane.showMessageDialog(null ,"Le nombre de place doit être un entier");
        }
        return ret;
    }

    public boolean already_exist(String numAvion){
            String requete="SELECT * FROM AVION WHERE NumAvion='"+numAvion+"'";
            boolean Vret=false;
            try{
                pst=conn.prepareStatement(requete);
                resultat= pst.executeQuery();
                if(resultat.next()){
                    Vret= true;
                }
                else{
                    Vret= false;
                }
                resultat.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            
            return Vret;
        }
    public boolean vol_exist(String NumVol){
        String requete="SELECT * FROM VOL WHERE NumVol='"+NumVol+"'";
                    boolean Vret=false;
            try{
                pst=conn.prepareStatement(requete);
                resultat= pst.executeQuery();
                if(resultat.next()){
                    Vret= true;
                }
                else{
                    Vret= false;
                    JOptionPane.showMessageDialog(null,"Numéro vol n'existe pas");
                }
                resultat.close();
                pst.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            return Vret;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numVol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numAvion = new javax.swing.JTextField();
        designation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombrePlaces = new javax.swing.JTextField();
        MODIFIER = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AIR MAD");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Numéro du vol :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 130, 40));

        numVol.setText("jTextField1");
        jPanel1.add(numVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 160, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Numéro Avion :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, 40));

        numAvion.setText("jTextField1");
        jPanel1.add(numAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 160, -1));

        designation.setText("jTextField1");
        jPanel1.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 160, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Désignation :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 130, 40));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre de places :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 180, 40));

        nombrePlaces.setText("jTextField1");
        jPanel1.add(nombrePlaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 160, -1));

        MODIFIER.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        MODIFIER.setForeground(new java.awt.Color(51, 51, 51));
        MODIFIER.setText("MODIFIER");
        MODIFIER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFIERActionPerformed(evt);
            }
        });
        jPanel1.add(MODIFIER, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 230, 40));

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });
        jPanel1.add(fermer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(605, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MODIFIERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFIERActionPerformed
         String req="UPDATE AVION set NumAvion='"+numAvion.getText()+"', Design='"+designation.getText()+"', NbPlaces="+nombrePlaces.getText()+", NumVol='"+numVol.getText()+"' WHERE NumAvion='"+oldNumAvion+"'";
        if(!oldNumAvion.equals(numAvion.getText()) && already_exist(numAvion.getText())){
                JOptionPane.showMessageDialog(null,"Il paraît que ce que vous modifier est déjà dedans");
        }
        else{
            if(vol_exist(numVol.getText())&&valid_nbplace(nombrePlaces.getText())){
                try {
                    pst=conn.prepareStatement(req);
                    pst.execute();
                    pst.close();
                    JOptionPane.showMessageDialog(null,"Modification effectuée avec succès");
                    if(oldNbPlace!=Integer.parseInt(nombrePlaces.getText())){
                        pst=conn.prepareStatement("DELETE FROM PLACE WHERE NumAvion='"+oldNumAvion+"'");
                        pst.execute();
                        pst.close();
                        String requete="INSERT INTO PLACE(NumAvion,NumPlace,Occupation,NumReservation) VALUES (?,?,?,?)";
                        StringBuilder NumPl=new StringBuilder();
                        for(int i=1;i<=Integer.parseInt(nombrePlaces.getText());i++) {
                            NumPl.append("PL");
                            NumPl.append(i);
                            try{
                                pst=conn.prepareStatement(requete);
                                pst.setString(1,oldNumAvion);
                                pst.setString(2, NumPl.toString());
                                pst.setInt(3, 0);
                                pst.setString(4, "");
                                pst.executeUpdate();
                                pst.close();
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,e);
                            }
                            NumPl.delete(0, NumPl.length());
                        }
                        //pst=conn.prepareStatement("UPDATE='"+numAvion.getText()+"' WHERE NumAvion)='"+oldNumAvion+"'");
                        //pst.execute();
                    }
                    if(!oldNumAvion.equals(numAvion.getText())){
                        pst=conn.prepareStatement("UPDATE PLACE SET NumAvion='"+numAvion.getText()+"' WHERE NumAvion='"+oldNumAvion+"'");
                        pst.execute();
                        pst.close();
                        pst=conn.prepareStatement("UPDATE RESERVATION SET NumAvion='"+numAvion.getText()+"' WHERE NumAvion='"+oldNumAvion+"'");
                        pst.execute();
                        pst.close();
                    }
                    men.listeAvions();
                    setVisible(false);
                }catch(HeadlessException | SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
        
    }//GEN-LAST:event_MODIFIERActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MODIFIER;
    private javax.swing.JTextField designation;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrePlaces;
    private javax.swing.JTextField numAvion;
    private javax.swing.JTextField numVol;
    // End of variables declaration//GEN-END:variables
}
