/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vol;
import Reservation.avionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Santatra
 */
public class AjoutVol extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    JVol vol=null;
    /**
     * Creates new form AjoutVol
     */
    public AjoutVol(JVol vol) {
        initComponents();
        con=avionDB.ConnectDB();
        this.vol=vol;
        NumVol_form.setText(suggestion_Id("V"));
        
        //combobox
        //JComboBox<String> comboBox = new JComboBox<>();
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        depart_form.setModel(comboBoxModel);

        // Ajout des données dynamiquement
        comboBoxModel.addElement("Option 1");
        comboBoxModel.addElement("Option 2");
        comboBoxModel.addElement("Option 3");

        // Exemple de mise à jour des données
        comboBoxModel.addElement("Nouvelle option");
    }
    
    public String suggestion_Id(String deb){
		int i=1;
		StringBuilder id=new StringBuilder();
		id.append(deb);
		id.append(i);
		while(already_exist(id.toString())) {
			id.delete(0, id.length());
			i++;
			id.append(deb);
			id.append(i);
		}
		return id.toString();
    }
    private boolean already_exist(String num){
        boolean ret=false;
        try{
            pst=con.prepareStatement("SELECT * FROM VOL WHERE NumVol='"+num+"'");
            rs=pst.executeQuery();
            if(rs.next()){
               ret=true;
            }
            pst.close();
            rs.close();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        return ret;
    }
    
    private boolean valid_frais(String montant){
        boolean ret=false;
        if(montant.matches("[+-]?\\d*(\\.\\d+)?")){
            ret=true;
        }else{
            JOptionPane.showMessageDialog(null ,"Le montant doit être composé de chiffre");
        }
        return ret;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumVol_form = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        frais_form = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        depart_form = new javax.swing.JComboBox<>();
        arrivee_form = new javax.swing.JComboBox<>();
        valider_btn = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("N°Vol:");

        jLabel2.setText("Frais:");

        jLabel3.setText("Ville d'arrivée:");

        jLabel4.setText("Ville de depart:");

        depart_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manakara", "Mananjary", "Farafangana", "Vangaindrano", "Fianarantsoa", "Antananarivo" }));

        arrivee_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manakara", "Mananjary", "Farafangana", "Vangaindrano", "Fianarantsoa", "Antananarivo" }));

        valider_btn.setText("VALIDER");
        valider_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_btnActionPerformed(evt);
            }
        });

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valider_btn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arrivee_form, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depart_form, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumVol_form)
                            .addComponent(frais_form))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumVol_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(depart_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivee_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(frais_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(valider_btn)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(475, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void valider_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_btnActionPerformed
        String numVol=NumVol_form.getText();
        String depart=depart_form.getSelectedItem().toString();
        String arrivee=arrivee_form.getSelectedItem().toString();
        Double frais=0.0;
        if(NumVol_form.getText().equals("")||frais_form.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tous les champs sont obligatoires");
        }else{
            
            if(already_exist(numVol)){
                JOptionPane.showMessageDialog(null,"Le numero est déjà utilisé");
            }
            else{
                if(depart_form.getSelectedItem().toString().equals(arrivee_form.getSelectedItem().toString())){
                    JOptionPane.showMessageDialog(null,"La ville de départ ne peut pas être la même que la ville d'arrivée");
                }
                else{
                    if(valid_frais(frais_form.getText())){
                        frais=Double.parseDouble(frais_form.getText());
                        try{
                            pst=con.prepareStatement("INSERT INTO VOL(NumVol,VilleDepart,VilleArrivée,frais) VALUES (?,?,?,?)");
                            pst.setString(1, NumVol_form.getText());
                            pst.setString(2, depart_form.getSelectedItem().toString());
                            pst.setString(3, arrivee_form.getSelectedItem().toString());
                            pst.setDouble(4,frais);
                            pst.executeUpdate();
                            pst.close();
                            JOptionPane.showMessageDialog(null,"Ajout avec succès");
                            vol.volList();
                            dispose();
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
            }
        }    
    }//GEN-LAST:event_valider_btnActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumVol_form;
    private javax.swing.JComboBox<String> arrivee_form;
    private javax.swing.JComboBox<String> depart_form;
    private javax.swing.JLabel fermer;
    private javax.swing.JTextField frais_form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton valider_btn;
    // End of variables declaration//GEN-END:variables
}
