/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vol;

import Reservation.avionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Santatra
 */
public class EditerVol extends javax.swing.JFrame {

    private Connection con=null;
    private PreparedStatement pst=null;
    private ResultSet rs=null;
    private String oldNum;
    private JVol vol;
    /**
     * Creates new form EditerVol
     */
    public EditerVol(String num,String depart,String arrivee,double frais,JVol vol) {
        initComponents();
        con=avionDB.ConnectDB();
        NumVol_form.setText(num);
        depart_form.setSelectedItem(depart);
        arrivee_form.setSelectedItem(arrivee);
        frais_form.setText(String.valueOf(frais));
        oldNum=num;
        this.vol=vol;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumVol_form = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        frais_form = new javax.swing.JTextField();
        depart_form = new javax.swing.JComboBox<>();
        arrivee_form = new javax.swing.JComboBox<>();
        valider_btn = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("N°Vol:");

        jLabel2.setText("Ville de départ:");

        jLabel3.setText("Ville d'arrivée:");

        jLabel4.setText("Frais:");

        depart_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manakara", "Mananjary", "Farafangana", "Vangaindrano", "Fianarantsoa", "Antananarivo" }));

        arrivee_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manakara", "Mananjary", "Farafangana", "Vangaindrano", "Fianarantsoa", "Antananarivo" }));

        valider_btn.setText("VALIDER");
        valider_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider_btnActionPerformed(evt);
            }
        });

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valider_btn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(arrivee_form, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depart_form, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumVol_form)
                        .addComponent(frais_form)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumVol_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(depart_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(arrivee_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frais_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(valider_btn)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(461, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void valider_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider_btnActionPerformed
        boolean valid=true;
        String depart=depart_form.getSelectedItem().toString();
        String arrivee=arrivee_form.getSelectedItem().toString();
        if(!oldNum.equals(NumVol_form.getText())){
            if(already_exist(NumVol_form.getText())){
                JOptionPane.showMessageDialog(null,"Le numero est déjà utilisé par une autre vol");
                valid=false;
            }
        }
        if(depart.equals(arrivee)){
            JOptionPane.showMessageDialog(null,"La ville de depart ne peut pas être le même la ville d'arrivée");
        }
        else{
            if(valid&&valid_frais(frais_form.getText())){
                try{
                    pst=con.prepareStatement("UPDATE VOL SET NumVol=?, VilleDepart=?, VilleArrivée=?,frais=? WHERE NumVol=?");
                    pst.setString(1, NumVol_form.getText());
                    pst.setString(2, depart_form.getSelectedItem().toString());
                    pst.setString(3, arrivee_form.getSelectedItem().toString());
                    pst.setString(4,frais_form.getText());
                    pst.setString(5,oldNum);
                    pst.executeUpdate();
                    pst.close();
                    JOptionPane.showMessageDialog(null,"Modification effectuée");
                    vol.volList();
                    dispose();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_valider_btnActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    private boolean already_exist(String num){
        boolean ret=false;
        try{
            pst=con.prepareStatement("SELECT * FROM VOL WHERE NumVol='"+num+"'");
            rs=pst.executeQuery();
            if(rs.next()){
               ret=true;
            }
            pst.close();
            rs.close();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        return ret;
    }
    
    private boolean valid_frais(String montant){
        boolean ret=false;
        if(montant.matches("[+-]?\\d*(\\.\\d+)?")){
            ret=true;
        }else{
            JOptionPane.showMessageDialog(null ,"Le montant doit être composé de chiffre");
        }
        return ret;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NumVol_form;
    private javax.swing.JComboBox<String> arrivee_form;
    private javax.swing.JComboBox<String> depart_form;
    private javax.swing.JLabel fermer;
    private javax.swing.JTextField frais_form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton valider_btn;
    // End of variables declaration//GEN-END:variables
}
