/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vol;

import Reservation.avionDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santatra
 */
public class JVol extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form JVol
     */
    public JVol() {
        initComponents();
        con=avionDB.ConnectDB();
        volList();
    }

   public void volList(){
        String req="SELECT * FROM VOL";
        try{
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            //int i=1;
            DefaultTableModel model=new DefaultTableModel(new String[]{
               "N°VOL","VILLE DE DEPART","VILLE D'ARRIVEE","FRAIS" 
            },0){
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("NumVol"),
                    rs.getString("VilleDepart"),
                    rs.getString("VilleArrivée"),
                    rs.getDouble("frais"),
                });
                //i++;
            }
            pst.close();
            rs.close();
            Vol_table.setModel(model);
            Vol_table.setRowHeight(25);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Vol_table = new javax.swing.JTable();
        nouveau_btn = new javax.swing.JButton();
        supprimer_btn = new javax.swing.JButton();
        editer_btn = new javax.swing.JButton();
        Rechercher_form = new javax.swing.JTextField();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Vol_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Vol_table);

        nouveau_btn.setText("Nouveau");
        nouveau_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveau_btnActionPerformed(evt);
            }
        });

        supprimer_btn.setText("SUPPRIMER");
        supprimer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer_btnActionPerformed(evt);
            }
        });

        editer_btn.setText("EDITER");
        editer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editer_btnActionPerformed(evt);
            }
        });

        Rechercher_form.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Rechercher_formKeyReleased(evt);
            }
        });

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nouveau_btn)
                        .addGap(26, 26, 26)
                        .addComponent(supprimer_btn)
                        .addGap(33, 33, 33)
                        .addComponent(editer_btn)
                        .addGap(57, 57, 57)
                        .addComponent(Rechercher_form, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(fermer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveau_btn)
                    .addComponent(supprimer_btn)
                    .addComponent(editer_btn)
                    .addComponent(Rechercher_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(560, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nouveau_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveau_btnActionPerformed
        AjoutVol vol=new AjoutVol(this);
        vol.show();
    }//GEN-LAST:event_nouveau_btnActionPerformed

    private void supprimer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer_btnActionPerformed
        if(Vol_table.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Veuillez selectionner le vol à supprimér");
        }
        else{
            int opt=JOptionPane.showConfirmDialog(null,"Voulez vous vraiment le supprimer","supprimer",JOptionPane.YES_NO_OPTION);
            if(opt==0){
                String num=String.valueOf(Vol_table.getValueAt(Vol_table.getSelectedRow(),0));
                String req="DELETE FROM VOL WHERE NumVol='"+num+"'";
                try{
                    pst=con.prepareStatement(req);
                    pst.executeUpdate();
                    pst.close();
                    JOptionPane.showMessageDialog(null,"Suppression effectué");
                    volList();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_supprimer_btnActionPerformed

    private void editer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editer_btnActionPerformed
        if(Vol_table.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Veuillez selectionner le vol à modifier");
        }else{
            String num=String.valueOf(Vol_table.getValueAt(Vol_table.getSelectedRow(),0));
            String dep=String.valueOf(Vol_table.getValueAt(Vol_table.getSelectedRow(),1));
            String arr=String.valueOf(Vol_table.getValueAt(Vol_table.getSelectedRow(),2));
            String frais=String.valueOf(Vol_table.getValueAt(Vol_table.getSelectedRow(),3));
            EditerVol edit=new EditerVol(num,dep,arr,Double.parseDouble(frais),this);
            edit.show();
            
        }
    }//GEN-LAST:event_editer_btnActionPerformed

    private void Rechercher_formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rechercher_formKeyReleased
        String search=Rechercher_form.getText();
        String req="SELECT * FROM VOL WHERE NumVol LIKE'%"+search+"%'OR VilleDepart LIKE '%"+search+"%' OR VilleArrivée LIKE '%"+search+"%'";
        try{
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            //int i=1;
            DefaultTableModel model=new DefaultTableModel(new String[]{
               "N°VOL","VILLE DE DEPART","VILLE D'ARRIVEE","FRAIS" 
            },0){
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("NumVol"),
                    rs.getString("VilleDepart"),
                    rs.getString("VilleArrivée"),
                    rs.getDouble("frais")
                });
                //i++;
            }
            pst.close();
            rs.close();
            Vol_table.setModel(model);
            Vol_table.setRowHeight(25);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Rechercher_formKeyReleased

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JVol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Rechercher_form;
    private javax.swing.JTable Vol_table;
    private javax.swing.JButton editer_btn;
    private javax.swing.JLabel fermer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nouveau_btn;
    private javax.swing.JButton supprimer_btn;
    // End of variables declaration//GEN-END:variables
}
