package Reservation;




//import Reservation.JReservation;
//²import Reservation.avionDB;
import Reservation.JReservation;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Santatra
 */
public class AjoutReservation extends javax.swing.JFrame {

    /**
     * Creates new form AjoutReservation
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    JReservation JRes=null;
    public AjoutReservation(JReservation Res) {
        initComponents();
        con=avionDB.ConnectDB();
        JRes=Res;
        NumReservation_form.setText(suggestion_Id("Res"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NumAvion_form = new javax.swing.JTextField();
        NumReservation_form = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NumPlace_form = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NomVoyageur_form = new javax.swing.JTextField();
        DateReservation_form = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        Valider_btn = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("NOUVELLE RESERVATION");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("N°Reservation:");
        jPanel2.add(jLabel2);

        jLabel3.setText("N°Avion:");

        NumAvion_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumAvion_formFocusLost(evt);
            }
        });

        jLabel4.setText("N°Place:");

        NumPlace_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumPlace_formFocusLost(evt);
            }
        });

        jLabel5.setText("Date de reservation:");

        jLabel6.setText("Nom du voyageur:");

        Valider_btn.setText("VALIDER");
        Valider_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valider_btnActionPerformed(evt);
            }
        });

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Valider_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumReservation_form)
                            .addComponent(NumAvion_form)
                            .addComponent(NumPlace_form)
                            .addComponent(DateReservation_form, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(NomVoyageur_form))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumReservation_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumAvion_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(NumPlace_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(DateReservation_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomVoyageur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(Valider_btn))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Valider_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valider_btnActionPerformed
        if(NumReservation_form.getText().equals("")||NumAvion_form.getText().equals("")||NumPlace_form.getText().equals("")||((JTextField)DateReservation_form.getDateEditor().getUiComponent()).getText().isEmpty()||NomVoyageur_form.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tous les champs sont obligatoires");
        }else{
            if(already_exist(NumReservation_form.getText())){
                JOptionPane.showMessageDialog(null, "L'identifiant est dejà utilisé");
            }
            else{
                if(Validation_Avion()&&Validation_Place()){
                    try{
                        SimpleDateFormat sp=new SimpleDateFormat("yyyy-MM-dd");
                        pst=con.prepareStatement("INSERT INTO RESERVATION(NumReservation,NumAvion,NumPlace,Date_Reservation,NomVoyageur) VALUES (?,?,?,?,?)");
                        pst.setString(1, NumReservation_form.getText());
                        pst.setString(2, NumAvion_form.getText());
                        pst.setString(3, NumPlace_form.getText());
                        pst.setString(4,sp.format(DateReservation_form.getDate()));
                        pst.setString(5, NomVoyageur_form.getText());
                        pst.executeUpdate();
                        pst.close();
                        pst=con.prepareStatement("UPDATE PLACE SET Occupation=1, NumReservation='"+NumReservation_form.getText()+"' WHERE NumAvion='"+NumAvion_form.getText()+"' and NumPlace='"+NumPlace_form.getText()+"'");
                        pst.executeUpdate();
                        pst.close();
                        JOptionPane.showMessageDialog(null, "Ajout avec succès");
                        //setVisible(false);
                        JRes.reservationList();
                        JRes.getNouveau_btn().setText("NOUVEAU");
                        JRes.getNouveau_btn().setEnabled(true);
                        dispose();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        }
    }//GEN-LAST:event_Valider_btnActionPerformed

    private void NumAvion_formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumAvion_formFocusLost
        Validation_Avion();
    }//GEN-LAST:event_NumAvion_formFocusLost

    private void NumPlace_formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumPlace_formFocusLost
        Validation_Place();
    }//GEN-LAST:event_NumPlace_formFocusLost

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        JRes.getNouveau_btn().setText("NOUVEAU");
        JRes.getNouveau_btn().setEnabled(true);
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    /**
     * @param args the command line arguments
     */
    private boolean Validation_Avion(){
        boolean ret=true;
        String numAvion=NumAvion_form.getText();
        if(!numAvion.equals("")){
            try{
                pst=con.prepareStatement("SELECT * FROM AVION WHERE NumAvion='"+numAvion+"'");
                rs=pst.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, "Le numero de l'avion n'existe pas");
                    ret=false;
                }
                pst.close();
                rs.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        return ret;
    }
    
    private boolean Validation_Place(){
        boolean ret=true;
        String numAvion=NumAvion_form.getText();
        String numPlace=NumPlace_form.getText();
        if(!numPlace.equals("")&&!numAvion.equals("")){
            try{
                pst=con.prepareStatement("SELECT * FROM PLACE WHERE NumAvion='"+numAvion+"' and NumPlace='"+numPlace+"'");
                rs=pst.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, " Cette place n'existe pas");
                    ret=false;
                }else{
                    if(rs.getInt("Occupation")==1){
                        JOptionPane.showMessageDialog(null, "Cette place n'est plus disponible");
                        ret=false;
                    }
                }
                pst.close();
                rs.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        return ret;
    }
    private boolean already_exist(String num){
        boolean ret=false;
        try{
            pst=con.prepareStatement("SELECT * FROM RESERVATION WHERE NumReservation='"+num+"'");
            rs=pst.executeQuery();
            if(rs.next()){
               ret=true;
            }
            pst.close();
            rs.close();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
        return ret;
    }
    public String suggestion_Id(String deb){
		int i=1;
		StringBuilder id=new StringBuilder();
		id.append(deb);
		id.append(i);
		while(already_exist(id.toString())) {
			id.delete(0, id.length());
			i++;
			id.append(deb);
			id.append(i);
		}
		return id.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateReservation_form;
    private javax.swing.JTextField NomVoyageur_form;
    private javax.swing.JTextField NumAvion_form;
    private javax.swing.JTextField NumPlace_form;
    private javax.swing.JTextField NumReservation_form;
    private javax.swing.JButton Valider_btn;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
