package Reservation;




//import Reservation.JReservation;
//import Reservation.avionDB;
import Reservation.JReservation;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Santatra
 */
public class EditerReservation extends javax.swing.JFrame {

    /**
     * Creates new form EditerReservation
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    JReservation JRes=null;
    String old_NumRes=null;
    String old_NumPlace=null;
    String old_NumAvion=null;
    public EditerReservation(String NumRes,String NumAv,String NumPl,String DateRes,String NomVoy,JReservation res) {
        initComponents();
        NumReservation_form.setText(NumRes);
        NumAvion_form.setText(NumAv);
        NumPlace_form.setText(NumPl);
        NomVoyageur_form.setText(NomVoy);
        try {
            Date date=(Date)new SimpleDateFormat("yyyy-MM-dd").parse(DateRes);
            DateReservation_form.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(EditerReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        old_NumRes=NumRes;
        old_NumPlace=NumPl;
        old_NumAvion=NumAv;
        JRes=res;
        con=avionDB.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private boolean Validation_Avion(){
        boolean ret=true;
        String numAvion=NumAvion_form.getText();
        if(!numAvion.equals("")){
            try{
                pst=con.prepareStatement("SELECT * FROM AVION WHERE NumAvion='"+numAvion+"'");
                rs=pst.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, "Le numero de l'avion n'existe pas");
                    ret=false;
                }
                pst.close();
                rs.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        return ret;
    }
    
    private boolean Validation_Place(){
        boolean ret=true;
        String numAvion=NumAvion_form.getText();
        String numPlace=NumPlace_form.getText();
        if(!numPlace.equals("")&&!numAvion.equals("")){
            try{
                pst=con.prepareStatement("SELECT * FROM PLACE WHERE NumAvion='"+numAvion+"' and NumPlace='"+numPlace+"'");
                rs=pst.executeQuery();
                if(!rs.next()){
                    JOptionPane.showMessageDialog(null, " Cette place n'existe pas");
                    ret=false;
                }else{
                    if(!old_NumPlace.equals(NumPlace_form.getText())||!old_NumAvion.equals(NumAvion_form.getText())){
                        if(rs.getInt("Occupation")==1){
                            JOptionPane.showMessageDialog(null, "Cette place n'est plus disponible");
                            ret=false;
                        }
                    }
                }
                pst.close();
                rs.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        return ret;
    }
    private boolean already_exist(String num){
        boolean ret=false;
        try{
                pst=con.prepareStatement("SELECT * FROM RESERVATION WHERE NumReservation='"+num+"'");
                rs=pst.executeQuery();
                if(rs.next()){
                    ret=true;
                }
                pst.close();
                rs.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        return ret;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumReservation_form = new javax.swing.JTextField();
        NomVoyageur_form = new javax.swing.JTextField();
        DateReservation_form = new com.toedter.calendar.JDateChooser();
        NumAvion_form = new javax.swing.JTextField();
        NumPlace_form = new javax.swing.JTextField();
        Valider_modif_btn = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("MODIFICATION DE RESERVATION");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("NumReseration:");

        jLabel3.setText("NumPlace:");

        jLabel4.setText("NumAvion:");

        jLabel5.setText("Date de reservation:");

        jLabel6.setText("Nom du Voyageur:");

        NumAvion_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumAvion_formFocusLost(evt);
            }
        });

        NumPlace_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NumPlace_formFocusLost(evt);
            }
        });

        Valider_modif_btn.setText("VALIDER");
        Valider_modif_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valider_modif_btnActionPerformed(evt);
            }
        });

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumReservation_form, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NomVoyageur_form)
                        .addComponent(DateReservation_form, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addComponent(NumPlace_form, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NumAvion_form))
                    .addComponent(Valider_modif_btn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NumReservation_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumAvion_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NumPlace_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(NomVoyageur_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DateReservation_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Valider_modif_btn)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NumAvion_formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumAvion_formFocusLost
        Validation_Avion();
    }//GEN-LAST:event_NumAvion_formFocusLost

    private void NumPlace_formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NumPlace_formFocusLost
        Validation_Place();
    }//GEN-LAST:event_NumPlace_formFocusLost

    private void Valider_modif_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valider_modif_btnActionPerformed
        boolean exist=false;
        int opt=JOptionPane.showConfirmDialog(null,"Voulez vous vraiment le modifier","supprimé",JOptionPane.YES_NO_OPTION);
        if(opt==0){
            if(NumReservation_form.getText().equals("")||NumAvion_form.getText().equals("")||NumPlace_form.getText().equals("")||((JTextField)DateReservation_form.getDateEditor().getUiComponent()).getText().isEmpty()||NomVoyageur_form.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Tous les champs sont obligatoires");
            }else{
                if(!old_NumRes.equals(NumReservation_form.getText())){
                    if(already_exist(NumReservation_form.getText())){
                        exist=true;
                        JOptionPane.showMessageDialog(null,"Identifiant dejà utilisé par une autre reservation");
                    }
                }
  
                    if(!exist&&Validation_Avion()&&Validation_Place()){
                        try{
                            SimpleDateFormat sp=new SimpleDateFormat("yyyy-MM-dd");
                            pst=con.prepareStatement("UPDATE RESERVATION SET NumReservation=?, NumAvion=?, NumPlace=?,Date_Reservation=?, NomVoyageur=? WHERE NumReservation=?");
                            pst.setString(1, NumReservation_form.getText());
                            pst.setString(2, NumAvion_form.getText());
                            pst.setString(3, NumPlace_form.getText());
                            pst.setString(4,sp.format(DateReservation_form.getDate()));
                            pst.setString(5, NomVoyageur_form.getText());
                            pst.setString(6, old_NumRes);
                            pst.executeUpdate();
                            if(!old_NumRes.equals(NumReservation_form.getText())){
                                     pst=con.prepareStatement("UPDATE PLACE SET NumReservation='"+NumReservation_form.getText()+"' WHERE NumAvion='"+old_NumAvion+"' and NumPlace='"+old_NumPlace+"'");
                                     pst.executeUpdate();
                                     pst.close();
                            }
                            if(!old_NumPlace.equals(NumPlace_form.getText())||!old_NumAvion.equals(NumAvion_form.getText())){
                                 pst=con.prepareStatement("UPDATE PLACE SET Occupation=1, NumReservation='"+NumReservation_form.getText()+"' WHERE NumAvion='"+NumAvion_form.getText()+"' and NumPlace='"+NumPlace_form.getText()+"'");
                                 pst.executeUpdate();
                                 pst.close();
                                 pst=con.prepareStatement("UPDATE PLACE SET Occupation=0, NumReservation='' WHERE NumAvion='"+old_NumAvion+"' and NumPlace='"+old_NumPlace+"'");
                                 pst.executeUpdate();
                                 pst.close();
                            }
                            JOptionPane.showMessageDialog(null, "Mise à jour effectuée");
                            //setVisible(false);
                            JRes.getEditer_btn().setText("EDITER");
                            JRes.getEditer_btn().setEnabled(true);
                            JRes.reservationList();
                            dispose();
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                
            }
        }
    }//GEN-LAST:event_Valider_modif_btnActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        JRes.getEditer_btn().setText("EDITER");
        JRes.getEditer_btn().setEnabled(true);
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateReservation_form;
    private javax.swing.JTextField NomVoyageur_form;
    private javax.swing.JTextField NumAvion_form;
    private javax.swing.JTextField NumPlace_form;
    private javax.swing.JTextField NumReservation_form;
    private javax.swing.JButton Valider_modif_btn;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
