package Reservation;




//import Reservation.avionDB;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Santatra
 */
public class JReservation extends javax.swing.JFrame {

    /**
     * Creates new form JReservation
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    Loading load=new Loading();
    public JReservation() {
        con=avionDB.ConnectDB();
        initComponents();
        reservationList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reservation_table = new javax.swing.JTable();
        annuler_btn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Rechercher_form = new javax.swing.JTextField();
        Nouveau_btn = new javax.swing.JButton();
        Editer_btn = new javax.swing.JButton();
        Supprimer_btn = new javax.swing.JButton();
        Histogramme_btn = new javax.swing.JButton();
        fermer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RESERVATION");

        Reservation_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Reservation_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reservation_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Reservation_table);

        annuler_btn.setText("ANNULER");
        annuler_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuler_btnActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridBagLayout());

        Rechercher_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rechercher_formActionPerformed(evt);
            }
        });
        Rechercher_form.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Rechercher_formKeyReleased(evt);
            }
        });

        Nouveau_btn.setText("NOUVEAU");
        Nouveau_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nouveau_btnActionPerformed(evt);
            }
        });

        Editer_btn.setText("EDITER");
        Editer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editer_btnActionPerformed(evt);
            }
        });

        Supprimer_btn.setText("SUPPRIMER");
        Supprimer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_btnActionPerformed(evt);
            }
        });

        Histogramme_btn.setText("Chart");
        Histogramme_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Histogramme_btnActionPerformed(evt);
            }
        });

        fermer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        fermer.setForeground(new java.awt.Color(255, 0, 0));
        fermer.setText("X");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 421, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Histogramme_btn)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rechercher_form, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nouveau_btn)
                                .addComponent(annuler_btn)
                                .addComponent(Editer_btn)
                                .addComponent(Supprimer_btn)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(annuler_btn)
                                .addGap(14, 14, 14)
                                .addComponent(Nouveau_btn)
                                .addGap(18, 18, 18)
                                .addComponent(Editer_btn)
                                .addGap(14, 14, 14)
                                .addComponent(Supprimer_btn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rechercher_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Histogramme_btn))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void annuler_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuler_btnActionPerformed
        recette("2022","AV1");
    }//GEN-LAST:event_annuler_btnActionPerformed

    private void Reservation_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reservation_tableMouseClicked
        String NumRes=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),0));
        String NumAv=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),1));
        String NumPl=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),2));
        String DateRes=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),3));
        String NomVoy=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),4));
    }//GEN-LAST:event_Reservation_tableMouseClicked

    private void Rechercher_formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rechercher_formKeyReleased
        String search=Rechercher_form.getText();
        String req="SELECT * FROM RESERVATION WHERE NumReservation LIKE'%"+search+"%'OR NumAvion LIKE '%"+search+"%' OR NumPlace LIKE '%"+search+"%' OR NomVoyageur LIKE '%"+search+"%'";
        try{
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            //int i=1;
            DefaultTableModel model=new DefaultTableModel(new String[]{
               "N°RESERVATION","N°AVION","N°PLACE","DATE DE RESERVATION","NOM DU VOYAGEUR" 
            },0){
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("NumReservation"),
                    rs.getString("NumAvion"),
                    rs.getString("NumPlace"),
                    rs.getString("Date_Reservation"),
                    rs.getString("NomVoyageur")
                });
                //i++;
            }
            pst.close();
            rs.close();
            Reservation_table.setModel(model);
            Reservation_table.setRowHeight(25);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Rechercher_formKeyReleased

    private void Nouveau_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nouveau_btnActionPerformed
        Nouveau_btn.setText("NOUVEAU...");
        Nouveau_btn.setEnabled(false);
        AjoutReservation Ares=new AjoutReservation(this);
        //Ares.setVisible(true);
        Ares.show();
    }//GEN-LAST:event_Nouveau_btnActionPerformed

    private void Supprimer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_btnActionPerformed
        if(Reservation_table.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Veuillez selectionner la reservation à supprimée");
        }else{
            int opt=JOptionPane.showConfirmDialog(null,"Voulez vous vraiment le supprimer","supprimé",JOptionPane.YES_NO_OPTION);
            if(opt==0){
                String Res=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),0));
                String Avion=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),1));
                String Place=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),2));
                String req="DELETE FROM RESERVATION WHERE NumReservation='"+Res+"'";
                try{
                    pst=con.prepareStatement(req);
                    pst.executeUpdate();
                    pst.close();
                    if(verif_res_place(Res)){
                        req="UPDATE PLACE SET Occupation='0', NumReservation='' WHERE NumAvion='"+Avion+"' and NumPlace='"+Place+"'";
                        pst=con.prepareStatement(req);
                        pst.executeUpdate();
                        pst.close();
                    }
                    JOptionPane.showMessageDialog(null,"Suppression effectué");
                    reservationList();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }
    }//GEN-LAST:event_Supprimer_btnActionPerformed

    private void Editer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editer_btnActionPerformed
        if(Reservation_table.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Veuillez selectionner la reservation à modifiée");
        }else{
            Editer_btn.setText("EDITER...");
            Editer_btn.setEnabled(false);
            String NumRes=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),0));
            String NumAv=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),1));
            String NumPl=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),2));
            String DateRes=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),3));
            String NomVoy=String.valueOf(Reservation_table.getValueAt(Reservation_table.getSelectedRow(),4));
            EditerReservation ERes=new EditerReservation(NumRes,NumAv,NumPl,DateRes,NomVoy,this);
            //ERes.setVisible(true);
            ERes.show();
        }
        
    }//GEN-LAST:event_Editer_btnActionPerformed

    private void Histogramme_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Histogramme_btnActionPerformed
        String annee=JOptionPane.showInputDialog("Veuillez entrer un année:");
        String req="SELECT  SUM(VOL.frais) AS recette, AVION.NumAvion FROM AVION,RESERVATION,VOL WHERE (VOL.NumVol=AVION.NumVol) AND (AVION.NumAVion=RESERVATION.NumAvion) AND (STRFTIME(\"%Y\",RESERVATION.Date_Reservation))=\""+annee+"\" GROUP BY AVION.NumAVION";
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        try {
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            while(rs.next()){
                dataset.setValue(rs.getDouble("recette"),"RECETTE",rs.getString("NumAvion"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        JFreeChart chart=ChartFactory.createBarChart("RECETTE ANNUELLE PAR AVION", "Numero Avion", "Recette", dataset, PlotOrientation.VERTICAL, false, true, false);
        //CategoryPlot p=chart.getCategoryPlot();
        //p.setRangeGridlinePaint(Color.red);
        ChartFrame frame=new ChartFrame("RECETTE ANNUELLE PAR AVION",chart);
        frame.setSize(450,350);
        frame.setVisible(true);
    }//GEN-LAST:event_Histogramme_btnActionPerformed

    private void Rechercher_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rechercher_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rechercher_formActionPerformed

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        dispose();
    }//GEN-LAST:event_fermerMouseClicked
    public boolean verif_res_place(String res){
        boolean ret=false;
        String req="SELECT * FROM PLACE WHERE NumReservation='"+res+"'";
        try {
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            if(rs.next()){
                ret=true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        return ret;
    }
    public void reservationList(){
        String req="SELECT * FROM RESERVATION";
        try{
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            //int i=1;
            DefaultTableModel model=new DefaultTableModel(new String[]{
               "N°RESERVATION","N°AVION","N°PLACE","DATE DE RESERVATION","NOM DU VOYAGEUR" 
            },0){
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("NumReservation"),
                    rs.getString("NumAvion"),
                    rs.getString("NumPlace"),
                    rs.getString("Date_Reservation"),
                    rs.getString("NomVoyageur")
                });
                //i++;
            }
            pst.close();
            rs.close();
            Reservation_table.setModel(model);
            Reservation_table.setRowHeight(25);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    public void recette(String annee,String avion){
        double somme=0;
        String req="SELECT SUM(VOL.frais) AS RECETTE, STRFTIME('%m',RESERVATION.Date_Reservation) AS MOIS FROM VOL,AVION,RESERVATION WHERE (VOL.NumVol=AVION.NumVol) AND (AVION.NumAVION=RESERVATION.NumAvion) AND STRFTIME('%Y',RESERVATION.Date_Reservation)=='"+annee+"'  AND AVION.NumAvion=='"+avion+"' GROUP BY STRFTIME('%m',RESERVATION.Date_Reservation) ORDER BY STRFTIME('%m',RESERVATION.Date_Reservation)";
        try{
            pst=con.prepareStatement(req);
            rs=pst.executeQuery();
            //int i=1;
            DefaultTableModel model=new DefaultTableModel(new String[]{
               "RECETTE","MOIS"
            },0){
                public boolean isCellEditable(int row ,int column){
                    return false;
                }
            };
            while(rs.next()){
                somme+=rs.getDouble("RECETTE");
                model.addRow(new Object[]{
                    rs.getString("RECETTE"),
                    mois_to_string(rs.getString("MOIS"))
                });
            }
            pst.close();
            rs.close();
            Reservation_table.setModel(model);
            Reservation_table.setRowHeight(25);
            JOptionPane.showMessageDialog(null, String.valueOf(somme));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public String mois_to_string(String nb){
        String ret="";
        switch(nb){
            case "01":
                ret="Janvier";
                break;
            case "02":
                ret="Fevrier";
                break;
            case "03":
                ret="Mars";
                break;
            case "04":
                ret="Avril";
                break;
            case "05":
                ret="Mai";
                break;
            case "06":
                ret="Juin";
                break;
            case "07":
                ret="Juillet";
                break;
            case "08":
                ret="Août";
                break;
            case "09":
                ret="Septembre";
                break;
            case "10":
                ret="Octobre";
                break;
            case "11":
                ret="Novembre";
                break;
            case "12":
                ret="Décembre";
                break;
            default :
                ret="Sampo agn";
        }
        return ret;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JReservation().setVisible(true);
            }
        });
    }
    public JButton getNouveau_btn(){
        return Nouveau_btn;
    }
    
    public JButton getEditer_btn(){
        return Editer_btn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editer_btn;
    private javax.swing.JButton Histogramme_btn;
    private javax.swing.JButton Nouveau_btn;
    private javax.swing.JTextField Rechercher_form;
    private javax.swing.JTable Reservation_table;
    private javax.swing.JButton Supprimer_btn;
    private javax.swing.JButton annuler_btn;
    private javax.swing.JLabel fermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
